// <auto-generated />
namespace Tiziano.MyBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class insert1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702211535379_insert1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
